version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    groups:
      gradle-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    commit-message:
      prefix: ui
      prefix-development: ui-dev
    schedule:
      interval: weekly
      day: friday
    cooldown:
      default-days: 2
    open-pull-requests-limit: 99
    groups:
      babel:
        patterns: [ "@babel/*" ]
      fontawesome:
        patterns: [ "@fortawesome/*" ]
      webpack:
        patterns: [ "webpack*", "*-loader", "*-webpack-plugin" ]
      eslint:
        patterns: [ "eslint*", "@eslint/*", "@types/eslint*" ]
